#!/usr/bin/env bash
# Failure drills (roadmap 9.18) on a local copy of the production stack: the
# reference compose stack (MySQL 8, Redis, migrate, API, web), the HTTPS edge
# and the monitoring stack (Prometheus with the repository's alerts.yml,
# Alertmanager, blackbox probes), with the inputs a drill needs written to
# DRILL_DIR (never inside the checkout). The fault hooks below are what
# scripts/drills/drill.mjs runs; against staging, the same driver runs with
# the staging commands instead (docs/DRILLS.md, "Running the drills on staging").
#
#   scripts/drills/drill-stack.sh up              build-free start (images dukaanai-api, -web, -db-ops must exist)
#   scripts/drills/drill-stack.sh run <drill>     one drill with this stack's hooks (see drill.mjs for the names)
#   scripts/drills/drill-stack.sh all             every drill in order, evidence in $DRILL_DIR/evidence
#                                                 (DRILL_UI=0: without the browser observer)
#   scripts/drills/drill-stack.sh down            stop and delete the stack and its volumes
#
# Hooks (called by the driver; usable by hand):
#   api-kill                 SIGKILL of the API process (a crash); the restart policy brings it back
#   mysql-stop | mysql-start, redis-stop | redis-start
#   storage-fill | storage-free   fill the documents volume to the last byte / remove the filler
#   tls valid|near|expired   install that edge certificate and reload the edge
#   restore-backup           db-ops backup (the dump the restore drill starts from)
#   restore-publish          binlog-archive --flush, then offsite push (the copy the restore reads)
#   restore-run              fetch the off-site copy into an empty volume, restore it to
#                            DRILL_TARGET_TIME into database dukaanai_restored, start an API on it
#   restore-cleanup          stop that API, drop the restored database
#   compose ARGS...          docker compose with the drill's project, env file and overlay
#
# Environment: DRILL_DIR (default /tmp/dukaanai-drill), DRILL_STORAGE_SIZE (64m),
# EDGE_HTTPS_PORT (8443), EDGE_HTTP_PORT (8080), DRILL_RESTORED_API_PORT (3012).
set -euo pipefail
cd "$(dirname "$0")/../.."

DRILL_DIR="${DRILL_DIR:-/tmp/dukaanai-drill}"
WEB_HOST="${WEB_HOST:-app.dukaanai.test}"
API_HOST="${API_HOST:-api.dukaanai.test}"
HTTPS_PORT="${EDGE_HTTPS_PORT:-8443}"
RESTORED_PORT="${DRILL_RESTORED_API_PORT:-3012}"
PROJECT=dukaanai-drill
ENV_FILE="$DRILL_DIR/drill.env"

# The drill names resolve to this machine: never send them through an HTTP proxy.
export NO_PROXY="${NO_PROXY:+$NO_PROXY,}$WEB_HOST,$API_HOST" no_proxy="${no_proxy:+$no_proxy,}$WEB_HOST,$API_HOST"
say() { printf '%s %s\n' "$(date -u +%H:%M:%S)" "$*"; }
die() { printf 'drill-stack: %s\n' "$*" >&2; exit 1; }
dc() { docker compose -p "$PROJECT" --env-file "$ENV_FILE" -f docker-compose.yml -f scripts/drills/compose.drill.yml --profile edge --profile ops "$@"; }
mysql_root() { dc exec -T mysql sh -c 'MYSQL_PWD="$MYSQL_ROOT_PASSWORD" mysql -uroot "$@"' -- "$@"; }

# --- inputs --------------------------------------------------------------------
write_env() {
  [ -f "$ENV_FILE" ] && return 0
  mkdir -p "$DRILL_DIR"
  (umask 077; : > "$ENV_FILE")
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/drills/drill-stack.sh for the local failure drills only.
JWT_SECRET=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -hex 32)
OFFSITE_CRYPT_PASSWORD=$(openssl rand -hex 32)
DRILL_DIR=$DRILL_DIR
DRILL_STORAGE_SIZE=${DRILL_STORAGE_SIZE:-64m}
WEB_HOST=$WEB_HOST
API_HOST=$API_HOST
WEB_ORIGIN=https://$WEB_HOST:$HTTPS_PORT
API_PUBLIC_URL=https://$API_HOST:$HTTPS_PORT/api
EDGE_HTTP_PORT=${EDGE_HTTP_PORT:-8080}
EDGE_HTTPS_PORT=$HTTPS_PORT
# The binary-log archive runs every 5 minutes, as in production.
BINLOG_ARCHIVE_INTERVAL_SECONDS=300
EOF
}

# A drill CA and three certificates for the edge names, all on one key:
# valid (90 days), near (expires in 3 days: inside the 14-day warning of
# DukaanAiCertificateExpiring) and expired (ended yesterday).
write_tls() {
  local d="$DRILL_DIR/tls"
  [ -f "$d/expired.crt" ] && return 0
  mkdir -p "$d/ca/newcerts"
  : > "$d/ca/index.txt"; echo 1000 > "$d/ca/serial"
  cat > "$d/ca/ca.cnf" <<EOF
[ca]
default_ca = drill
[drill]
dir = $d/ca
database = \$dir/index.txt
new_certs_dir = \$dir/newcerts
serial = \$dir/serial
certificate = $d/ca.crt
private_key = $d/ca.key
default_md = sha256
policy = anything
unique_subject = no
copy_extensions = none
x509_extensions = leaf
[anything]
commonName = supplied
[leaf]
basicConstraints = critical, CA:false
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:$WEB_HOST, DNS:$API_HOST
EOF
  openssl req -x509 -newkey rsa:2048 -nodes -keyout "$d/ca.key" -out "$d/ca.crt" -days 365 \
    -subj "/CN=DukaanAI drill CA" -addext "basicConstraints=critical,CA:true" -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null
  openssl req -newkey rsa:2048 -nodes -keyout "$d/edge.key" -out "$d/edge.csr" -subj "/CN=$WEB_HOST" 2>/dev/null
  local fmt='+%Y%m%d%H%M%SZ'
  sign() { openssl ca -batch -config "$d/ca/ca.cnf" -in "$d/edge.csr" -out "$d/$1.crt" -notext \
    -startdate "$(date -u -d "$2" "$fmt")" -enddate "$(date -u -d "$3" "$fmt")" >/dev/null 2>&1 || die "could not sign the $1 certificate"; }
  sign valid '-1 day' '+90 days'
  sign near '-1 day' '+3 days'
  sign expired '-30 days' '-1 day'
  cp "$d/valid.crt" "$d/edge.crt"
  cat /etc/ssl/certs/ca-certificates.crt "$d/ca.crt" > "$d/ca-bundle.crt"
  chmod 0644 "$d"/*.crt "$d/edge.key"
}

# The repository's prometheus.yml with its commented public targets enabled
# under the edge names: the same edit an operator makes on staging.
write_prometheus() {
  sed -e "s|# - https://api.example.com/|- https://$API_HOST/|" \
      -e "s|# - https://app.example.com/|- https://$WEB_HOST/|" \
      deploy/prometheus/prometheus.yml > "$DRILL_DIR/prometheus.yml"
  chmod 0644 "$DRILL_DIR/prometheus.yml"
  grep -q "https://$API_HOST/api/health/ready" "$DRILL_DIR/prometheus.yml" && grep -q "https://$WEB_HOST/login" "$DRILL_DIR/prometheus.yml" \
    || die "deploy/prometheus/prometheus.yml no longer carries the commented public probe targets this script enables"
}

hosts_entry() {
  getent hosts "$WEB_HOST" >/dev/null && getent hosts "$API_HOST" >/dev/null && return 0
  if [ -w /etc/hosts ]; then
    echo "127.0.0.1 $WEB_HOST $API_HOST" >> /etc/hosts; say "added $WEB_HOST and $API_HOST to /etc/hosts (127.0.0.1)"
  elif sudo -n true 2>/dev/null; then
    echo "127.0.0.1 $WEB_HOST $API_HOST" | sudo tee -a /etc/hosts >/dev/null; say "added $WEB_HOST and $API_HOST to /etc/hosts (127.0.0.1, sudo)"
  else
    die "$WEB_HOST and $API_HOST must resolve to this machine: add '127.0.0.1 $WEB_HOST $API_HOST' to /etc/hosts"
  fi
}

drill_env() { # the driver's environment for this stack
  cat <<EOF
export DRILL_API_URL=https://$API_HOST:$HTTPS_PORT
export DRILL_WEB_URL=https://$WEB_HOST:$HTTPS_PORT
export DRILL_PROMETHEUS_URL=http://127.0.0.1:${PROMETHEUS_PORT:-9090}
export DRILL_ALERTMANAGER_URL=http://127.0.0.1:${ALERTMANAGER_PORT:-9093}
export DRILL_RESTORED_API_URL=http://127.0.0.1:$RESTORED_PORT
export NODE_EXTRA_CA_CERTS=$DRILL_DIR/tls/ca.crt
export DRILL_STATE_FILE=$DRILL_DIR/drill-account.json
export DRILL_EVIDENCE_DIR=$DRILL_DIR/evidence
export DRILL_HOOK="bash $(pwd)/scripts/drills/drill-stack.sh"
export NO_PROXY="$NO_PROXY" no_proxy="$no_proxy"
EOF
}

# One drill: the driver, and beside it (DRILL_UI=1, the default) the browser
# observer of apps/web/e2e-drills on the drills a browser can see. The
# certificate drill is observed by the driver's verifying client (the
# observer ignores the drill CA), the restore drill on the restored API.
run_drill() {
  local drill="$1" stamp obs_pid="" rc
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  if [ "${DRILL_UI:-1}" = "1" ] && [ "$drill" != tls-expiry ] && [ "$drill" != offsite-restore ]; then
    export DRILL_OBSERVER_REPORT="$DRILL_EVIDENCE_DIR/$drill-$stamp-screen.jsonl" DRILL_OBSERVER_STOP_FILE="$DRILL_DIR/observer.stop"
    rm -f "$DRILL_OBSERVER_STOP_FILE" "$DRILL_OBSERVER_STOP_FILE.fault"
    (cd apps/web && DRILL_WEB_URL="https://$WEB_HOST:$HTTPS_PORT" DRILL_HOST_RESOLVER="MAP $WEB_HOST 127.0.0.1, MAP $API_HOST 127.0.0.1" \
      npx playwright test --config playwright.drill.config.ts > "$DRILL_EVIDENCE_DIR/$drill-$stamp-observer.log" 2>&1) &
    obs_pid=$!
  else
    unset DRILL_OBSERVER_REPORT DRILL_OBSERVER_STOP_FILE
  fi
  set +e
  node scripts/drills/drill.mjs "$drill"; rc=$?
  set -e
  if [ -n "$obs_pid" ]; then : > "$DRILL_OBSERVER_STOP_FILE"; wait "$obs_pid" || say "browser observer exited non-zero (see $DRILL_EVIDENCE_DIR/$drill-$stamp-observer.log)"; fi
  return "$rc"
}

# --- commands ------------------------------------------------------------------
cmd="${1:-}"; shift || true
case "$cmd" in
  up)
    write_env; write_tls; write_prometheus; hosts_entry
    mkdir -p "$DRILL_DIR/offsite"; chmod 0777 "$DRILL_DIR/offsite"
    for img in dukaanai-api dukaanai-web dukaanai-db-ops; do docker image inspect "$img" >/dev/null 2>&1 || die "image $img is missing: build it first (docker compose build, or the release images retagged)"; done
    say "starting the stack (project $PROJECT)"
    dc up -d --wait mysql redis migrate api web edge prometheus alertmanager blackbox
    dc up -d binlog-archiver
    say "first backups of every kind, so the backup alerts start green"
    dc run --rm -T db-ops backup --label drill-start >/dev/null
    dc run --rm -T db-ops binlog-archive --flush >/dev/null
    dc run --rm -T db-ops documents-backup --label drill-start >/dev/null
    dc run --rm -T db-ops offsite push >/dev/null
    curl -sf --noproxy "*" --cacert "$DRILL_DIR/tls/ca.crt" "https://$API_HOST:$HTTPS_PORT/api/health/ready" >/dev/null || die "the API is not ready through the edge"
    say "stack up; driver environment:"; drill_env
    ;;
  env) drill_env ;;
  down) dc down -v --remove-orphans ;;
  compose) dc "$@" ;;

  api-kill)
    pid="$(docker inspect -f '{{.State.Pid}}' "$(dc ps -q api)")"
    [ -n "$pid" ] && [ "$pid" != 0 ] || die "the API container is not running"
    kill -9 "$pid"; say "API process $pid killed (SIGKILL)" ;;
  mysql-stop) dc stop mysql >/dev/null; say "mysql stopped" ;;
  mysql-start) dc start mysql >/dev/null; say "mysql started" ;;
  redis-stop) dc stop redis >/dev/null; say "redis stopped" ;;
  redis-start) dc start redis >/dev/null; say "redis started" ;;
  storage-fill)
    dc exec -T api sh -c 'dd if=/dev/zero of="$STORAGE_ROOT/.drill-fill" bs=1M 2>/dev/null; df -h "$STORAGE_ROOT" | tail -n 1' ;;
  storage-free)
    dc exec -T api sh -c 'rm -f "$STORAGE_ROOT/.drill-fill"; df -h "$STORAGE_ROOT" | tail -n 1' ;;
  tls)
    state="${1:?tls valid|near|expired}"; [ -f "$DRILL_DIR/tls/$state.crt" ] || die "no $state certificate"
    cp "$DRILL_DIR/tls/$state.crt" "$DRILL_DIR/tls/edge.crt"
    dc exec -T edge caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile --force >/dev/null 2>&1 || die "caddy reload failed"
    say "edge certificate: $state ($(openssl x509 -in "$DRILL_DIR/tls/edge.crt" -noout -enddate))" ;;

  restore-backup)
    dc run --rm -T db-ops backup --label drill-restore | tail -n 2 ;;
  restore-publish)
    dc run --rm -T db-ops binlog-archive --flush | tail -n 1
    dc run --rm -T db-ops offsite push | tail -n 2 ;;
  restore-run)
    : "${DRILL_TARGET_TIME:?DRILL_TARGET_TIME (UTC, YYYY-MM-DD HH:MM:SS) is required}"
    docker volume rm -f "${PROJECT}_drill-restore" >/dev/null 2>&1 || true
    say "fetching the off-site copy into an empty volume"
    dc run --rm -T -v "${PROJECT}_drill-restore:/restore" db-ops offsite fetch /restore | tail -n 2
    say "restoring the latest dump of that copy, rolled forward to $DRILL_TARGET_TIME UTC, into dukaanai_restored"
    dc run --rm -T -v "${PROJECT}_drill-restore:/restore" --entrypoint sh db-ops -c \
      'dump="$(ls -1 /restore/*.sql.gz | sort | tail -n 1)"; echo "dump: $(basename "$dump")"; exec bash /scripts/db/restore.sh "$dump" --database dukaanai_restored --create --yes --to "$1" --binlogs /restore/binlog' \
      -- "$DRILL_TARGET_TIME" | tail -n 6
    mysql_root -e "GRANT ALL PRIVILEGES ON dukaanai_restored.* TO 'dukaanai'@'%'"
    say "starting an API on the restored database (port $RESTORED_PORT, its own Redis db so no cached figure of the abandoned timeline is served)"
    docker rm -f "${PROJECT}-api-restored" >/dev/null 2>&1 || true
    # The live API's own connection string, pointed at the restored database.
    live_url="$(docker exec "$(dc ps -q api)" printenv DATABASE_URL)"
    restored_url="$(printf '%s' "$live_url" | sed -E 's#/([A-Za-z0-9_]+)(\?|$)#/dukaanai_restored\2#')"
    dc run -d --no-deps --name "${PROJECT}-api-restored" -p "$RESTORED_PORT:3002" \
      -e "DATABASE_URL=$restored_url" -e REDIS_URL=redis://redis:6379/3 -e CRON_ENABLED=false api >/dev/null
    for _ in $(seq 1 90); do curl -sf --noproxy "*" "http://127.0.0.1:$RESTORED_PORT/api/health/ready" >/dev/null 2>&1 && { say "restored API ready"; exit 0; }; sleep 1; done
    docker logs --tail 30 "${PROJECT}-api-restored" >&2; die "the API on the restored database did not become ready" ;;
  restore-cleanup)
    docker rm -f "${PROJECT}-api-restored" >/dev/null 2>&1 || true
    mysql_root -e "DROP DATABASE IF EXISTS dukaanai_restored"
    docker volume rm -f "${PROJECT}_drill-restore" >/dev/null 2>&1 || true ;;

  run)
    eval "$(drill_env)"; mkdir -p "$DRILL_EVIDENCE_DIR"
    run_drill "${1:?run <drill>}" ;;
  all)
    eval "$(drill_env)"; mkdir -p "$DRILL_EVIDENCE_DIR"; rc=0
    for drill in api-kill mysql-stop redis-stop storage-full tls-expiry offsite-restore; do
      run_drill "$drill" || rc=1
    done
    exit "$rc" ;;
  *) sed -n '2,30p' "$0"; exit 2 ;;
esac
